---
- hosts: arista 
  connection: local
  gather_facts: no

  tasks:
  - name: Gather Space info from Show File Systems
    eos_command:
      commands: bash df -h | grep flash
      provider: "{{ eos_connection }}"
    register: result

  - debug: 
      msg: "{{ result.stdout }}"
