---
- hosts: arista 
  connection: local
  gather_facts: no

  tasks:
  - name: Gather info from Show Extensions
    eos_command:
      commands: show extensions
      provider: "{{ eos_connection }}"
    register: result

  - name: Create csv file
    template:
      src: "csv.j2"
      dest: "$WORKSPACE/extensions.csv"
    run_once: true
