---
- hosts: arista 
  connection: local
  gather_facts: no

  tasks:
  - name: Gather info from Show MLAG
    eos_command:
      commands: show mlag
      provider: "{{ eos_connection }}"
    register: result

  - debug: 
      msg: "{{ result.stdout[0].peerLinkStatus }}"
