---
- hosts: arista 
  connection: local
  gather_facts: no

  tasks:
  - name: Gather info from Show Environment
    eos_command:
      commands: show environment power
      provider: "{{ eos_connection }}"
    register: result

  - debug: 
      msg: "{{ result.stdout_lines[0].powerSupplies }}"
